INSERT INTO mahasiswa (id, name)
VALUES (1, 'asep'),
(2, 'ade'),
(3, 'saipul'),
(4, 'asde'),
(5, 'asep'),
(6, 'asep'),
(7, 'asep'),
(8, 'asep'),
(9, 'asep'),
(10, 'asep'),
(11, 'asep'),
(12, 'ade'),
(13, 'saipul'),
(14, 'asde'),
(15, 'asep'),
(16, 'asep'),
(17, 'asep'),
(18, 'asep'),
(19, 'asep'),
(20, 'asep');